version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: aymenbraiek2019/sample-app:0.0.1-SNAPSHOT
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "28080:8080"
    networks:
       - webnet
networks:
webnet: